Fix nightly build of ls (#8969)
Followup for #8906

This PR fixes two things, broken in
991ce4bd59f81fbf2e256bd563f84ddd7e33a728:
- when checking for SCM version, we were looking for gel-server,
- we were (trying) to run tests.

I've added package.basename to targets, so we can dynamically look for
correct packages.

I've disabled running tests. We should be running them and I see that
there are some variables to support filtering test files, but I don't
know what exactly is wrong when the tests report the following:

```
Error: test path '/gel/share/tests' does not exist
```

So the tests are disabled for now, I hope elvis can help.